# Generated by Django 6.0.4 on 2026-05-09 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание работ')),
                ('meeting_date', models.DateTimeField(verbose_name='Дата встречи')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон для связи')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Причина отказа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='backend_api.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
