# Generated by Django 6.0.4 on 2026-05-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='meeting_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
