# Generated by Django 6.0.4 on 2026-06-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_service_moderated_at_service_moderated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_from',
            field=models.BooleanField(default=False, verbose_name='Цена от'),
        ),
    ]
